name: Publish Open Textbook

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
    paths-ignore:
      - 'manuscript/**'
      - 'README.md'

jobs:
  publish_textbook:
    runs-on: ubuntu-20.04
    steps:
      
      - name: Download Source Files
        uses: actions/checkout@v2
      
      - name: Setup Pandoc
        run: brew install pandoc

      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v1

      - name: TeX Dependencies
        run: |
          tlmgr --version
          tlmgr install $(cat lib/latex-packages.txt)

      - name: Build Website
        run: |
          bash lantern.sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy HTML to NUL Servers
        run: |
          aws s3 sync ./public/ ${{ secrets.AWS_S3_BUCKET_NAME }} --delete
          
      - name: Clear CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_CLOUDFRONT_DIST_ID }} \
            --paths "/*"
